### ISSUE TITLE
How generate the occupancy label visualization?

### ISSUE THREAD

**Issue by rockywind** [zhangyp15/OccFormer#3]
Hi,
Thank you for sharing the great work!
I want to visualize the occupancy label like the demo.
But I don't know how to do it.
Can you help me?

**Comment by zhangyp15** [comment]
Hi, thanks for your interest. I think the easiest way is to modify from the [test-function](https://github.com/zhangyp15/OccFormer/blob/67019eb1064e413efd6f723309f9981ee0801f11/projects/mmdet3d_plugin/occformer/apis/test.py#L22) by the following:
(1) simply browse the dataloder to get the images and ground-truth occupancy labels
(2) replace the output_voxels into the function `save_output_semantic_kitti` by the gt_occupancy from the dataloader.

Then you can visualize the saved files following the [demo pipeline](https://github.com/zhangyp15/OccFormer/blob/main/projects/mmdet3d_plugin/visualize/visualize_kitti.py#L1).
