### ISSUE TITLE
Have you ever try origin bev_encoder？

### ISSUE THREAD

**Issue by LMerCy** [zhangyp15/OccFormer#5]
Have you ever try origin bev_encoder of bevdepth, how about it's performance?

**Comment by zhangyp15** [comment]
Yes, the bev-encoder from bevdepth performs slightly worse than the transformer encoder. You can refer to the 3D ResNet-16 entry in the ablation study on encoders (Table 4).

**Comment by LMerCy** [comment]
> Yes, the bev-encoder from bevdepth performs slightly worse than the transformer encoder. You can refer to the 3D ResNet-16 entry in the ablation study on encoders (Table 4).

Thanks for your work! Could you provide a config of this?

**Comment by zhangyp15** [comment]
Sure. 

You can check [occformer_3dconv.zip](https://github.com/zhangyp15/OccFormer/files/11291781/occformer_3dconv.zip), which includes the config, the 3d resnet module, and our training log from the previous implementation.

**Comment by LMerCy** [comment]
> occformer_3dconv.zip

Thanks!
