### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/panoptic/v1.0-trainval/9c1a84e36b054b92ba0b1fcfbc023796_panoptic.npz'"

### ISSUE THREAD

**Issue by rockywind** [zhangyp15/OccFormer#6]
Hi, Thank you for your sharing the great code.
When I run the script `bash tools/dist_train.sh projects/configs/occformer_nusc/occformer_nusc_panoptic_r50_256x704_my.py 2`,
I met the error . How can I generate the `*_panoptic.npz`.

**Comment by zhangyp15** [comment]
You should download the nuScenes-panoptic dataset. 

BTW, the code for panoptic occformer is not carefully experimented. We provide it as an easier interface for future work.
